#!/usr/bin/env bash

BASE="$(dirname `readlink -m $0`)/.."

# Uncomment and specify to use your own wallabag codebase
# SOURCEPATH='/home/bob/Work/wallabag'           # Absolute path to wallabag sources

IMAGENAME='wallabag:latest'
TOOL_IMG='gdm85/trusty'

WALLABAGSOURCE='wallabag-source'
WALLABAG='wallabag-server'

function getStatus(){
    CONTAINER_ID=$(docker ps -a | grep -v Exit | grep $WALLABAG | awk '{print $1}')
    if [ -z $CONTAINER_ID ] ; then
        echo 'Not running.'
        return 1
    else
        IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_ID)
        cat<<EOF
Running in container: $CONTAINER_ID
IP address: $IP
Web server on:
 http://$(docker port $CONTAINER_ID 80)
 https://$(docker port $CONTAINER_ID 443)
EOF
        return 0
    fi
}

case "$1" in
    start)
	SALT=$(<$BASE/salt)

        VOLUMES="-v $BASE/data:/var/www/wallabag/db -v $BASE/webserver/ssl.key:/etc/ssl/wallabag.key -v $BASE/webserver/ssl.crt:/etc/ssl/wallabag.pem"

        if [ -n "$SOURCEPATH" ]; then
            docker ps -a | grep -q $WALLABAGSOURCE
            if [ $? -ne 0 ]; then
                docker run --name $WALLABAGSOURCE -v $SOURCEPATH:/var/www/wallabag $TOOL_IMG true
                VOLUMES="--volumes-from $WALLABAGSOURCE $VOLUMES"
            fi
        fi

        docker ps -a | grep -v Exit | grep -q $WALLABAG
        if [ $? -ne 0 ]; then
            echo "Now running: docker run --env WALLABAG_SALT=$SALT -d --name $WALLABAG $VOLUMES -p=4443:443 -p=8080:80 $IMAGENAME /sbin/my_init --enable-insecure-key"
            CONTAINER_ID=$(docker run --env WALLABAG_SALT=$SALT -d --name $WALLABAG $VOLUMES -p=4443:443 -p=8080:80 $IMAGENAME /sbin/my_init --enable-insecure-key)
        fi
        getStatus
        ;;

    status)
        getStatus
        ;;

    stop)
        CONTAINER_ID=$(docker ps -a | grep -v Exit | grep $WALLABAG | awk '{print $1}')
        if [[ -n $CONTAINER_ID ]] ; then
            SV=$(docker stop $CONTAINER_ID)
            SV=$(docker rm $CONTAINER_ID)
            if [ $? -eq 0 ] ; then
                echo 'Stopped.'
                if [ -n "$SOURCEPATH" ]; then
                    SRC=$(docker ps -a | grep $WALLABAGSOURCE | awk '{print $1}')
                    SRC=$(docker rm $SRC)
                fi
            fi
        else
            echo 'Not running.'
            exit 1
        fi
        ;;

    *)
        echo "Usage: `basename $0` {start|stop|status}"
        exit 1
        ;;
esac

exit 0
